### B_FIQ0w_R-IHDZGx2j7X9C2IZEJl-SVJN3AKAnhwLk4
POST http://localhost:3000/current-state
Content-Type: application/json

{
  "contractId": "B_FIQ0w_R-IHDZGx2j7X9C2IZEJl-SVJN3AKAnhwLk4"
}

### XQkGzXG6YknJyy-YbakEZvQKAWkW2_aPRhc3ShC8lyA
POST http://localhost:3000/current-state
Content-Type: application/json

{
  "contractId": "XQkGzXG6YknJyy-YbakEZvQKAWkW2_aPRhc3ShC8lyA"
}
